swagger: "2.0"
info:
  version: "1.0.0"
  title: "sprint project"
host: localhost:4200
basePath: /
schemes:
  - http
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  "/api/sprint":
    get:
      description: "get all sprints"
      summary: "get sprints tab"
      consumes: []
      produces:
        - applications/json
        - text/json
      responses:
        "200":
          description: list of sprint
          schema:
            type: array
            items:
              $ref: "#/definitions/sprint"
      deprecated: false
    post:
      description: "add a new sprint"
      summary: " new sprint"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "add  an object that need to be added"
          required: true
          schema:
            $ref: "#/definitions/sprint"
      responses:
        "201":
          description: "succes add"

definitions:
  sprint:
    type: "object"
    properties:
      idUser:
        type: string
      length:
        type: string
      status:
        type: string
      date:
        type: string
      start:
        type: string
      finish:
        type: string
      description:
        type: string
